import {
  Bot,
  Search,
  Scale,
  BarChart2,
  FileText,
  PenLine,
  DollarSign,
  Shield,
  Lock,
  Building2,
  ClipboardList,
  TrendingUp,
  BookOpen,
  AlertTriangle,
  Calculator,
  Users,
  Briefcase,
  Globe,
  Layers,
  MessageSquare,
  Lightbulb,
  Database,
  Code2,
  CheckSquare,
  type LucideIcon,
} from "lucide-react"

const ICON_MAP: Record<string, LucideIcon> = {
  // Emoji → Lucide
  "🔍": Search,
  "⚖️": Scale,
  "📊": BarChart2,
  "📄": FileText,
  "✍️": PenLine,
  "💰": DollarSign,
  "🤖": Bot,
  "🛡️": Shield,
  "🔒": Lock,
  "🏛️": Building2,
  "📋": ClipboardList,
  "📈": TrendingUp,
  "📚": BookOpen,
  "⚠️": AlertTriangle,
  "🧮": Calculator,
  "👥": Users,
  "💼": Briefcase,
  "🌍": Globe,
  "🗂️": Layers,
  "💬": MessageSquare,
  "💡": Lightbulb,
  "🗄️": Database,
  "💻": Code2,
  "✅": CheckSquare,
  // Name → Lucide (for programmatic use)
  Search: Search,
  Scale: Scale,
  BarChart2: BarChart2,
  FileText: FileText,
  PenLine: PenLine,
  DollarSign: DollarSign,
  Bot: Bot,
  Shield: Shield,
  Lock: Lock,
  Building2: Building2,
  ClipboardList: ClipboardList,
  TrendingUp: TrendingUp,
  BookOpen: BookOpen,
  AlertTriangle: AlertTriangle,
  Calculator: Calculator,
  Users: Users,
  Briefcase: Briefcase,
}

export function getAgentIcon(icon: string): LucideIcon {
  return ICON_MAP[icon] ?? Bot
}
