export default function PrivacyPolicyPage() {
  return (
    <article className="mx-auto max-w-3xl px-6 py-24 sm:px-8">
      <header className="mb-12">
        <h1 className="mb-3 text-3xl font-semibold tracking-tight sm:text-4xl">
          Privacy Policy
        </h1>
        <p className="text-sm text-muted-foreground">Last updated: May 2026</p>
      </header>

      <div className="space-y-10 text-sm leading-relaxed text-muted-foreground">
        <section>
          <h2 className="mb-3 text-base font-semibold text-foreground">
            1. Who We Are
          </h2>
          <p>
            Vera AI Solutions operates the Vera AI platform, an intelligent
            auditing workspace that enables audit professionals to build,
            configure, and converse with AI agents powered by Anthropic Claude
            models. This Privacy Policy explains what personal data we collect,
            why we collect it, how it is processed, and what rights you have
            over it.
          </p>
          <p className="mt-3">
            By creating an account or using any part of the Vera AI platform,
            you agree to the practices described in this policy. If you do not
            agree, please do not use the platform.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-base font-semibold text-foreground">
            2. Data We Collect
          </h2>
          <p className="mb-3">We collect data in the following categories:</p>

          <h3 className="mb-2 text-sm font-semibold text-foreground">
            Account and Identity Data
          </h3>
          <p className="mb-3">
            When you register, we collect your email address, display name, and
            a hashed password if you use email authentication. If you register
            via Google OAuth, we receive your Google profile name, email
            address, and profile picture URL. We assign you an internal user ID,
            a role (Admin, User, or Viewer), and subscription status.
          </p>

          <h3 className="mb-2 text-sm font-semibold text-foreground">
            Chat and Conversation Data
          </h3>
          <p className="mb-3">
            All messages you send and all responses generated by the AI are
            stored in our database. This includes the full text of your prompts,
            AI-generated replies, model selections, timestamps, and structured
            message parts such as tool calls or reasoning blocks. Chat
            transcripts are retained until you delete them. Completed turn pairs
            are stored separately for usage accounting and to enable our chat
            history memory feature.
          </p>

          <h3 className="mb-2 text-sm font-semibold text-foreground">
            Uploaded Files
          </h3>
          <p className="mb-3">
            You may upload PDF and Word documents during a chat session or to a
            knowledge base linked to an agent. PDF files are stored in Supabase
            cloud storage. Word documents have their text extracted server-side
            and the extracted text is stored as part of the message record.
            Files are retained until you delete them. Files used within a
            session but not explicitly saved to a knowledge base are not
            persisted beyond that session.
          </p>

          <h3 className="mb-2 text-sm font-semibold text-foreground">
            Agent and Knowledge Base Data
          </h3>
          <p className="mb-3">
            When you create a custom agent, we store its name, icon, system
            prompt, output format configuration, and any files linked to it in a
            knowledge base. This data is retained until you delete the agent or
            associated files.
          </p>

          <h3 className="mb-2 text-sm font-semibold text-foreground">
            Saved Memory
          </h3>
          <p className="mb-3">
            If you use the memory feature, you may explicitly save context notes
            that persist across chat sessions. These saved memories, including
            any revision history, are stored in our database and are retained
            until you delete them. You can disable this feature in your account
            settings.
          </p>

          <h3 className="mb-2 text-sm font-semibold text-foreground">
            Usage and Billing Data
          </h3>
          <p className="mb-3">
            We maintain an append-only ledger of usage events recording the
            number of AI requests made, the model used, your active plan,
            billing interval, and the approximate character count of inputs and
            outputs. This data is used to enforce plan limits, calculate
            billing, and generate usage dashboards. Stripe, our payment
            processor, handles all payment card data. We do not store credit
            card numbers or full card details.
          </p>

          <h3 className="mb-2 text-sm font-semibold text-foreground">
            Profile and Preferences
          </h3>
          <p>
            We store your profile avatar image, display name, and account
            preferences including memory settings. Avatar images are stored in
            Supabase cloud storage.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-base font-semibold text-foreground">
            3. How We Use Your Data
          </h2>
          <p className="mb-3">
            We use the data we collect for the following purposes:
          </p>
          <ul className="list-disc space-y-2 pl-5">
            <li>
              To create and manage your account and authenticate you securely.
            </li>
            <li>
              To provide the core Vera AI service, including delivering
              AI-generated responses to your messages.
            </li>
            <li>
              To send your uploaded files to Anthropic Claude via the Anthropic
              API to generate contextually relevant responses.
            </li>
            <li>
              To enforce plan-based request limits and calculate billing through
              Stripe.
            </li>
            <li>
              To surface relevant prior context from your chat history and saved
              memories in new conversations where you have this feature enabled.
            </li>
            <li>
              To allow you to build and configure AI agents with custom system
              prompts and knowledge-base documents.
            </li>
            <li>
              To send transactional emails such as account confirmation,
              password reset, and billing receipts.
            </li>
            <li>
              To detect, investigate, and prevent fraud, abuse, and security
              incidents.
            </li>
            <li>To comply with legal obligations.</li>
          </ul>
          <p className="mt-3">
            We do not use your conversation content to train or fine-tune AI
            models. We do not sell your personal data to any third party.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-base font-semibold text-foreground">
            4. Third-Party Services
          </h2>
          <p className="mb-3">
            We rely on the following third-party services to operate the
            platform:
          </p>
          <ul className="list-disc space-y-3 pl-5">
            <li>
              <span className="font-medium text-foreground">Anthropic</span> —
              Your messages, uploaded document content, and agent system prompts
              are transmitted to Anthropic&apos;s API to generate AI responses.
              Anthropic&apos;s privacy policy governs how they process that
              data. We transmit only what is necessary to fulfil your request.
            </li>
            <li>
              <span className="font-medium text-foreground">Supabase</span> — We
              use Supabase for PostgreSQL database hosting, file storage, and
              authentication. Your account data, chat transcripts, files, and
              memories are stored in Supabase infrastructure.
            </li>
            <li>
              <span className="font-medium text-foreground">Stripe</span> —
              Stripe processes all subscription payments. When you subscribe,
              you interact directly with Stripe&apos;s payment interface. We
              receive billing status and subscription metadata from Stripe via
              webhooks but do not receive or store your raw payment card
              details.
            </li>
            <li>
              <span className="font-medium text-foreground">Vercel</span> — The
              Vera AI application is hosted on Vercel&apos;s infrastructure.
              Request logs and performance data may be collected by Vercel in
              accordance with their data processing agreement.
            </li>
            <li>
              <span className="font-medium text-foreground">Google</span> — If
              you use Google OAuth to sign in, Google transmits your name, email
              address, and profile picture to our authentication provider. We do
              not receive your Google password or access to your Google account
              beyond the initial sign-in.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="mb-3 text-base font-semibold text-foreground">
            5. Data Security
          </h2>
          <p className="mb-3">
            We implement security measures appropriate to the nature of the data
            we handle:
          </p>
          <ul className="list-disc space-y-2 pl-5">
            <li>
              All data is encrypted in transit using TLS. Data stored in
              Supabase is encrypted at rest.
            </li>
            <li>
              Row-level security (RLS) is enforced on all database tables,
              ensuring that users can only access their own data.
            </li>
            <li>
              Anthropic API keys, Supabase service-role keys, and Stripe secret
              keys are stored only in server-side environment variables and are
              never exposed to client-side code or browser environments.
            </li>
            <li>
              All user-facing forms validate inputs with Zod schemas before any
              database write is performed.
            </li>
            <li>
              Stripe webhook events are validated against a signature header
              before being processed.
            </li>
            <li>Admin-only routes verify role server-side on every request.</li>
          </ul>
          <p className="mt-3">
            No security system is perfect. If you discover a vulnerability,
            please report it through our Responsible Disclosure Policy.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-base font-semibold text-foreground">
            6. Data Retention
          </h2>
          <p className="mb-3">
            We retain your data for as long as your account is active. Specific
            retention rules:
          </p>
          <ul className="list-disc space-y-2 pl-5">
            <li>
              Chat transcripts and messages are retained until you delete them
              or delete your account.
            </li>
            <li>
              Files uploaded to chat sessions but not saved to a knowledge base
              are not persistently stored beyond the session.
            </li>
            <li>
              Files added to a knowledge base are retained until you remove them
              from the knowledge base or delete the associated agent.
            </li>
            <li>
              Usage event records are retained for billing and auditing purposes
              for a minimum of 12 months.
            </li>
            <li>
              Upon account deletion, your profile, chats, agents, memories, and
              files are permanently removed. Billing records and usage ledger
              entries may be retained for legal and financial compliance
              purposes.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="mb-3 text-base font-semibold text-foreground">
            7. Your Rights
          </h2>
          <p className="mb-3">
            Depending on your jurisdiction, you may have the following rights
            regarding your personal data:
          </p>
          <ul className="list-disc space-y-2 pl-5">
            <li>
              <span className="font-medium text-foreground">Access</span> —
              request a copy of the data we hold about you.
            </li>
            <li>
              <span className="font-medium text-foreground">Correction</span> —
              request that inaccurate data be corrected.
            </li>
            <li>
              <span className="font-medium text-foreground">Deletion</span> —
              request that your data be deleted. You can initiate this directly
              from your account settings or by contacting us.
            </li>
            <li>
              <span className="font-medium text-foreground">Portability</span> —
              request a machine-readable export of your data.
            </li>
            <li>
              <span className="font-medium text-foreground">Objection</span> —
              object to certain processing activities.
            </li>
            <li>
              <span className="font-medium text-foreground">
                Withdrawal of consent
              </span>{" "}
              — where processing is based on consent, you may withdraw it at any
              time.
            </li>
          </ul>
          <p className="mt-3">
            To exercise any of these rights, contact us at{" "}
            <a
              href="mailto:info@veraaisolutions.com.au"
              className="text-foreground underline underline-offset-2 hover:opacity-70"
            >
              info@veraaisolutions.com.au
            </a>
            . We will respond within 30 days.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-base font-semibold text-foreground">
            8. Cookies and Tracking
          </h2>
          <p>
            We use session cookies issued by Supabase Auth to maintain your
            authenticated session. These are strictly necessary for the platform
            to function and are not used for advertising or cross-site tracking.
            We do not use third-party analytics tracking scripts, advertising
            pixels, or fingerprinting technologies.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-base font-semibold text-foreground">
            9. Children
          </h2>
          <p>
            The Vera AI platform is intended for professional use by adults. We
            do not knowingly collect personal data from individuals under the
            age of 16. If you believe we have inadvertently collected data from
            a minor, please contact us immediately and we will delete it.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-base font-semibold text-foreground">
            10. Changes to This Policy
          </h2>
          <p>
            We may update this Privacy Policy from time to time. Material
            changes will be communicated to registered users via email or an
            in-platform notice at least 14 days before they take effect. Your
            continued use of the platform after the effective date constitutes
            acceptance of the revised policy.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-base font-semibold text-foreground">
            11. Contact
          </h2>
          <p>
            For privacy enquiries or data subject requests, contact us at:{" "}
            <a
              href="mailto:info@veraaisolutions.com.au"
              className="text-foreground underline underline-offset-2 hover:opacity-70"
            >
              info@veraaisolutions.com.au
            </a>
            .
          </p>
        </section>
      </div>
    </article>
  )
}
